# Generated by Django 4.1.7 on 2023-03-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypost", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
